version: '3.9'
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  pub_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pub_service
    command: python pub.py
    depends_on:
      - redis

  sub_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sub_service
    command: python sub.py
    depends_on:
      - redis

  inference_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inference_service
    command: python inference_service.py
    depends_on:
      - redis
      - db

  db:
    image: postgres:alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
