# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: preprocessing.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'preprocessing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13preprocessing.proto\"*\n\x0b\x44\x61taRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07numbers\x18\x02 \x03(\x05\"=\n\x06Result\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03sum\x18\x02 \x01(\x05\x12\x0c\n\x04\x64iff\x18\x03 \x01(\x05\x12\x0c\n\x04mult\x18\x04 \x01(\x05\x32\x37\n\x0c\x44\x61taStreamer\x12\'\n\nStreamData\x12\x0c.DataRequest\x1a\x07.Result(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'preprocessing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATAREQUEST']._serialized_start=23
  _globals['_DATAREQUEST']._serialized_end=65
  _globals['_RESULT']._serialized_start=67
  _globals['_RESULT']._serialized_end=128
  _globals['_DATASTREAMER']._serialized_start=130
  _globals['_DATASTREAMER']._serialized_end=185
# @@protoc_insertion_point(module_scope)
